server.port=8082

spring.application.name=tournament-service

logging.level.org.springframework.security=DEBUG

jwt.secret=rsdXhhgtN/3eiyHyMEcRtngQmshXcmAXIJqzW+rDoXo=
jwt.expiration-ms=36000000
jwt.issuer=sports-tournament-system

# ==============================
# MySQL
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/sports_user_db
spring.datasource.username=root
spring.datasource.password=96321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# Kafka
# ==============================

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties[spring.json.add.type.headers]=false
# Consumer
spring.kafka.consumer.properties[spring.json.use.type.headers]=false
spring.kafka.consumer.group-id=tournament-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties[spring.json.value.default.type]=com.praneesh.sports.tournament_service.dto.event.TournamentCompletedEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.praneesh.sports.tournament_service.dto.event