server.port= 8082

spring.application.name= tournament-service

logging.level.org.springframework.security=DEBUG

jwt.secret=rsdXhhgtN/3eiyHyMEcRtngQmshXcmAXIJqzW+rDoXo=
jwt.expiration-ms=36000000
jwt.issuer= sports-tournament-system

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/sports_user_db

spring.datasource.username=root
spring.datasource.password=96321
# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties[spring.json.add.type.headers]=false