spring.application.name=competition-service
server.port=8084

# ==============================
# MySQL
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/competition_db
spring.datasource.username=root
spring.datasource.password=96321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# JWT
# ==============================

jwt.secret=rsdXhhgtN/3eiyHyMEcRtngQmshXcmAXIJqzW+rDoXo=
jwt.expiration-ms=36000000
jwt.issuer=sports-tournament-system

# ==============================
# Services
# ==============================

services.team.url=http://localhost:8081
services.tournament.url=http://localhost:8082

# ==============================
# Kafka
# ==============================

# ==============================
# Kafka
# ==============================

# ==============================
# Kafka
# ==============================

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties[spring.json.add.type.headers]=false